In [7]:
import pandas as pd
import numpy as np
import math

In [2]:
a1 = np.array([1, 2, None, 8])
a1

array([1, 2, None, 8], dtype=object)

In [3]:
%timeit np.arange(1E6, dtype=int).sum()

537 μs ± 4.11 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [4]:
%timeit np.arange(1E6, dtype=object).sum()

27.3 ms ± 185 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [6]:
a1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [17]:
a2 = np.array([1, 2, np.nan, 8])
a2

array([ 1.,  2., nan,  8.])

In [20]:
np.isnan(math.nan)

np.True_

In [21]:
s1 = pd.Series([1, math.nan, 4, None])
s1

0    1.0
1    NaN
2    4.0
3    NaN
dtype: float64

In [22]:
s2 = pd.Series(range(5), dtype=int)
s2

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [25]:
s2[0] = None

In [26]:
s2

0    NaN
1    1.0
2    2.0
3    3.0
4    4.0
dtype: float64

In [35]:
s3 = pd.Series([1, np.nan, 3, None, 5, pd.NA, 7], dtype="Float64")
s3

0     1.0
1    <NA>
2     3.0
3    <NA>
4     5.0
5    <NA>
6     7.0
dtype: Float64

In [45]:
s4 = pd.Series([1, np.nan, 2, math.nan])
s4[s4.notna()]

0    1.0
2    2.0
dtype: float64

In [38]:
pd.isna(s4), s4.isnull(), s4.isna()

(0    False
 1     True
 2    False
 3     True
 dtype: bool,
 0    False
 1     True
 2    False
 3     True
 dtype: bool,
 0    False
 1     True
 2    False
 3     True
 dtype: bool)

In [39]:
pd.notnull(s4), pd.notna(s4)

(0     True
 1    False
 2     True
 3    False
 dtype: bool,
 0     True
 1    False
 2     True
 3    False
 dtype: bool)

In [40]:
df = pd.DataFrame([[None, 2], [1, np.nan]])
df

     0    1
0  NaN  2.0
1  1.0  NaN

In [41]:
df.isnull()

       0      1
0   True  False
1  False   True

In [43]:
df[df.isnull()]

    0   1
0 NaN NaN
1 NaN NaN

In [47]:
df1 = pd.DataFrame([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], columns=list("abc"))
df1

     a    b    c
0  1.0  2.0  3.0
1  4.0  5.0  6.0

In [48]:
df2 = df1.copy()
df2

     a    b    c
0  1.0  2.0  3.0
1  4.0  5.0  6.0

In [49]:
s1 = df1.mean()
s1

a    2.5
b    3.5
c    4.5
dtype: float64

In [50]:
df2

     a    b    c
0  1.0  2.0  3.0
1  4.0  5.0  6.0

In [51]:
df2 + s1

     a    b     c
0  3.5  5.5   7.5
1  6.5  8.5  10.5