## 分层索引

- https://pandas.pydata.org/docs/user_guide/advanced.html
- https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html#pandas.MultiIndex

In [1]:
import pandas as pd
import numpy as np

In [3]:
index = [('California', 2010), ('California', 2020),
         ('New York', 2010), ('New York', 2020),
         ('Texas', 2010), ('Texas', 2020)]
populations = [37253956, 39538223,
               19378102, 20201249,
               25145561, 29145505]
pop = pd.Series(populations, index=pd.MultiIndex.from_tuples(index))
pop

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [8]:
pop.unstack().stack()

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [6]:
idx.levshape

(3, 2)

In [10]:
pop_df = pd.DataFrame({
    "total": pop,
    "under18": [9284094, 8898092, 4318033, 4181528, 6879014, 7432474]
})
pop_df

                    total  under18
California 2010  37253956  9284094
           2020  39538223  8898092
New York   2010  19378102  4318033
           2020  20201249  4181528
Texas      2010  25145561  6879014
           2020  29145505  7432474

In [11]:
f_u18 = pop_df["under18"] / pop_df["total"]
f_u18

California  2010    0.249211
            2020    0.225050
New York    2010    0.222831
            2020    0.206994
Texas       2010    0.273568
            2020    0.255013
dtype: float64

In [12]:
pop_df["f_u18"]=f_u18

In [13]:
pop_df

                    total  under18     f_u18
California 2010  37253956  9284094  0.249211
           2020  39538223  8898092  0.225050
New York   2010  19378102  4318033  0.222831
           2020  20201249  4181528  0.206994
Texas      2010  25145561  6879014  0.273568
           2020  29145505  7432474  0.255013